pkgname: cryptomator

# relative to squashfs-root
desktop_file: org.cryptomator.Cryptomator.desktop
icon: usr/share/icons/hicolor/512x512/apps/org.cryptomator.Cryptomator.png

desktop_replace: |
  Exec=$appimagebin %F

# https://github.com/cryptomator/cryptomator/releases
pkgver: 1.17.1
sha256sum: 290d30f81535483d01f1a799d380c90c2a194a0b6151418ac636f0f015d0372a
source_url: https://github.com/cryptomator/cryptomator/releases/download/$pkgver/cryptomator-$pkgver-x86_64.AppImage

gpg_identity: 'Good signature from "Cryptobot <releases@cryptomator.org>"'
gpg_primary: 5811 7AFA 1F85 B3EE C154  677D 615D 449F E6E6 A235
gpg_signature_url: https://github.com/cryptomator/cryptomator/releases/download/$pkgver/cryptomator-$pkgver-x86_64.AppImage.asc

# sha256sum

# Exec=AppRun --no-sandbox %U

# # relative to squashfs-root
# icon_location
# desktop_location
