pkgname: cryptomator

# relative to squashfs-root
desktop_file: org.cryptomator.Cryptomator.desktop
icon: usr/share/icons/hicolor/512x512/apps/org.cryptomator.Cryptomator.png

desktop_replace: |
  Exec=$appimagebin %F

# https://github.com/cryptomator/cryptomator/releases
pkgver: 1.15.1
sha256sum: 0873ed665202493e3b00ecdb8ec9fd2d5b5d318089fb5cf048c045278772e3ba
source_url: https://github.com/cryptomator/cryptomator/releases/download/$pkgver/cryptomator-$pkgver-x86_64.AppImage

gpg_identity: 'Good signature from "Cryptobot <releases@cryptomator.org>"'
gpg_primary: 5811 7AFA 1F85 B3EE C154  677D 615D 449F E6E6 A235
gpg_signature_url: https://github.com/cryptomator/cryptomator/releases/download/$pkgver/cryptomator-$pkgver-x86_64.AppImage.asc

# sha256sum

# Exec=AppRun --no-sandbox %U

# # relative to squashfs-root
# icon_location
# desktop_location
