pkgname: joplinapp-desktop

# relative to squashfs-root
desktop_file: joplin.desktop
icon: usr/share/icons/hicolor/512x512/apps/joplin.png

desktop_replace: |
  Exec=$appimagebin --no-sandbox %U

# https://github.com/laurent22/joplin/releases
pkgver: 3.3.13
# use $pkgver as placeholder for version in url

source_url: https://github.com/laurent22/joplin/releases/download/v$pkgver/Joplin-$pkgver.AppImage

sha512sum: 1e9a8867766f398a4efbc7066cf7940cf3affa208e5a7ca3f240d25e57879b633e122d78ec7066c2152b21e369a313881fd0fc189a11edc7aa10d7ba6eb4984b