pkgname: keepassxc

# relative to squashfs-root
desktop_file: org.keepassxc.KeePassXC.desktop
icon: usr/share/icons/hicolor/256x256/apps/keepassxc.png

desktop_replace: |
  Exec=$appimagebin %f
  TryExec=$appimagebin


pkgver: 2.7.9
sha256sum: 2a868b681a8ec4e381ac14203aec3d80ff6fa7a535fa102265a3ec9329b4b846

source_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage

gpg_identity: 'Good signature from "KeePassXC Release <release@keepassxc.org>"'
gpg_primary: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
gpg_signature_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage.sig
