pkgname: keepassxc

# relative to squashfs-root
desktop_file: org.keepassxc.KeePassXC.desktop
icon: usr/share/icons/hicolor/256x256/apps/keepassxc.png

desktop_replace: |
  Exec=$appimagebin %f
  TryExec=$appimagebin

# https://github.com/keepassxreboot/keepassxc/tags
pkgver: 2.7.10
sha256sum: 3f8308a4d905d067367d541b4dccd5e80700798039046ffc388ede4f50887b36

source_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage

gpg_identity: 'Good signature from "KeePassXC Release <release@keepassxc.org>"'
gpg_primary: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
gpg_signature_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage.sig
