pkgname: keepassxc

# relative to squashfs-root
desktop_file: org.keepassxc.KeePassXC.desktop
icon: usr/share/icons/hicolor/256x256/apps/keepassxc.png

desktop_replace: |
  Exec=$appimagebin %f
  TryExec=$appimagebin

# https://github.com/keepassxreboot/keepassxc/tags
pkgver: 2.7.12
sha256sum: 564fe8b751b9ef7aa057e4d3d0b2878db24eaa0f6b1c855c82e699ab0913ae49

source_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage

gpg_identity: 'Good signature from "KeePassXC Release <release@keepassxc.org>"'
gpg_primary: BF5A 669F 2272 CF43 24C1  FDA8 CFB4 C216 6397 D0D2
gpg_signature_url: https://github.com/keepassxreboot/keepassxc/releases/download/$pkgver/KeePassXC-$pkgver-x86_64.AppImage.sig
