pkgname: lunatask

# relative to squashfs-root
desktop_file: lunatask.desktop
icon: lunatask.png

desktop_replace: |
  Exec=$appimagebin --no-sandbox --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto %U

# https://github.com/lunatask/lunatask/releases/
pkgver: 2.1.15
# use $pkgver as placeholder for version in url

source_url: https://github.com/lunatask/lunatask/releases/download/v$pkgver/Lunatask-$pkgver.AppImage

# or sha256sum
sha256sum: 91bdedf1f426268833c89fcb92a3865a175630580f6dfce30fa9b98c35a4e118